### ISSUE TITLE
Blog information

### ISSUE THREAD

**Issue by shivaamm** [Pandz18/Pandz18#2]
Hello pandz18!! 
I'm Shivam Singhal you commented on one repository so i just wanted to have an update of that blog.
"Hey , I wanted to make a blog and was wondering with your permission if I could use your Repository as examples for a blog ?

I will show your name as well as link your repository so for anyone interested can contribute too .

I shall only do so , once you give me the ok for sharing your repository ."

This is what you commented, actually i have a similar repo and i'm still learning and growing so i thought your blog could help me. 
here's my repo link - https://github.com/shivaamm/Coding-Practice

I'm looking forward to hear from you soon.

**Comment by Pandz18** [comment]
Hi Shivam , 

Thank you , will let you know soon 👍
